### PR TITLE
Draft: Add option to change puzzle difficulty 

### PR DESCRIPTION
**Pull request by wbarnha**
Something that's been bothering me is that I have the option to modify the difficulty of puzzles on my Lichess browser application, but I can't do the same on mobile.

The code is currently pretty messy and not completely functional yet. Would there be any interest in this feature?

### CODE REVIEW

**Comment by jas14** [comment]
I and many others have a lot of interest in [puzzles V2](https://github.com/veloce/lichobile/issues/1480) generally :) which includes:

- difficulty options
- theme selection
- [dashboard](https://lichess.org/training/dashboard/30/dashboard)
- [history](https://lichess.org/training/history)
- a lot of UI work, much of which we can probably take from the website

We might want to wrap this work up into that - up to veloce!

**Comment by wbarnha** [comment]
I definitely think Puzzles V2 is a good thing to work towards, but it seems there's going to be some refactoring in the future to achieve that.

**Comment by wbarnha** [comment]
I support the idea of moving forward with puzzles V2, but from what I currently see, it'll require a substantial change in how lichobile interfaces with the server.

**Comment by wbarnha** [comment]
I saw the PR in https://github.com/lichess-org/lila/pull/10118. I like how there's more functionality to get puzzles batches by theme. But I'd still really like to see more added on for difficulty, so progress will need to wait.

**Comment by wbarnha** [comment]
I'm closing this PR because 1) it's getting messy, and 2) there's some additional work that needs to be done in localization before I'd enable support for themes. The backend for lila still needs some work some to support difficulty, but we can take measures to support puzzle themes in the meantime.

**Pull request closed without merging**
